# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "1.11.0"

  on_macos do
    on_arm do
      sha256 "2efefc4c0c9e767eed2691507a56b8aa5980e346abd9084ef123c2783ec43c8a"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b6db30868489e39f970461af26b98f66c3deb6e2a8f33bea8df2cb5cf769a70"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97fc8d5b475195ed029c89b438009e4510ef6ca53469e2e2355bf93d0e2f7581"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "014183710b4ede5fddb781502f9c8853c47b741000d30278999dceb9a85f23ca"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergon"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required
end
