# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "1.11.1"

  on_macos do
    on_arm do
      sha256 "7908d37cf7c8b200c84a0aeed4c2520e19c8627f6cdda7d6757f35160d3fcc3f"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b8aff5656facc29529da799278649847d98996bd7dd474d377fee4088853cab"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0db03b1c3bd4dba44b8ee05d1c92f822fe38606538e191be0f55f03e1b0dcde0"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe953164d2f4045f6b9af090802167b894f386378e325f5283c0efd4ca91a5ff"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergon"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required
end
