# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-codec" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "3e8ea326fc25d8bf089513abd8c2c2cb771e3905541f596eaf41f3acc3de88d9"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2722a51ec2aa83f0451e70b6976ed381d0521288d0e990d54f02b3145b5eef61"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2091bb27f79e7835926aca7e8f32d6958ffe69ce7d51eac2c996065a419861c0"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddaef08172cf7a6c0451361debc14c90bee1f247c0755d627a19947d1fedec4e"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "protoc-gen-codec"
  desc "A protoc plugin that emits proto3 marshal/unmarshal methods on your existing Go types."
  homepage "https://github.com/thesmos-ai/protoc-gen-codec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-codec-go"

  # No zap stanza required

end
