# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-codec" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "2480cfbec7d65c04a06008555130fd04216c17f5b1cf67f3631e27bf8d2442f9"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b6238040ac824f4903a25bda20ac2554a4236a7861de9b40551b6618add21c6"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c13b1f3c2fe66b5097a70935294e2aa09daea83025158cb327296fd58c13f22"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d89c0df2161de3cc46fc1645e0ecb323c41a9d87b555e037da3b3d70e1dbec03"
      url "https://github.com/thesmos-ai/protoc-gen-codec/releases/download/v#{version}/protoc-gen-codec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "protoc-gen-codec"
  desc "A protoc plugin that emits proto3 marshal/unmarshal methods on your existing Go types."
  homepage "https://github.com/thesmos-ai/protoc-gen-codec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-codec-go"

  # No zap stanza required

end
